### ISSUE TITLE
[Feature] Speed up normalization

### ISSUE THREAD

**Issue by b-per** [bruin-data/ingestr#9]
I have run a quick test, moving a 2M rows table from Snowflake to Snowflake.

It took ~4 min locally, with 3 min being spent at the "normalization" stage. 
The data being already in a table, couldn't we request the schema to the DB directly and then use it when calling `dlt`?

I also tried to replicate the same tables with [Sling](https://slingdata.io/) and it took ~ 1 min to run.

If the normalization time can be cut down, the perf would then be quite close to the Sling one..

**Comment by karakanb** [comment]
Hey, thanks a lot for taking the time and the benchmark here, much appreciated.

I am not much familiar with how dlt normalizes the data internally, I'll take a deeper look at this and have a conversation with the dlt folks on what we can do here.

**Comment by karakanb** [comment]
Since this is an ongoing work and gets better with each release, I'll close this for now. Happy to continue the conversation and take suggestions on this, but we are limited by how dlt approaches things.
